---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: back
  name: back-svc
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: back
  type: ClusterIP