---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: db
  name: "postgres"
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP
