---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 'pv-prod-{{ .Release.Name }}'
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv
