---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: 'front-{{ .Release.Name | replace "." "-" }}'
spec:
  replicas: {{ .Values.front.replicaCount }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: '{{ .Values.front.image }}:{{ .Values.front.tag }}'
          name: front
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: 'http://back-{{ .Release.Name | replace "." "-" }}.{{ .Values.namespace }}.svc.cluster.local:9000'
      restartPolicy: Always
