---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - image: dmi3x3/13-kubernetes-config_backend
          ports:
            - containerPort: 9000
              name: backend
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres.prod.svc.cluster.local:5432/news
          name: back
          volumeMounts:
            - mountPath: "/static"
              name: prod-volume
      restartPolicy: Always
      volumes:
        - name: prod-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-prod
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: back
  name: back-svc
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: back
  type: ClusterIP
